name: Motore GorlaNews

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  avvia-scraper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Scarica i file
        uses: actions/checkout@v4

      - name: Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa librerie
        run: pip install requests beautifulsoup4 firebase-admin

      - name: Esegui lo scraper
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }} # <-- QUESTA RIGA Ãˆ FONDAMENTALE!
        run: python scraper.py
